name: 'retail_sales'
version: '1.0.0'
profile: 'analysis_challenge'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
flags:
  send_anonymous_usage_stats: False

clean-targets:
  - "target"
  - "dbt_packages"
